name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      working-directory: ./bluetooth-speaker-laravel
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: bluetooth-speaker-laravel/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      working-directory: ./bluetooth-speaker-laravel
      run: composer install --ignore-platform-reqs

    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.PRIVATE_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: '-o IdentitiesOnly=yes'
        src: '/bluetooth-speaker-laravel/*'
        dest: 'music@challenger.tiar.be:/home/music/webapps/music-backend/'
    
    - name: SSH Setup
      # You may pin to the exact commit or the version.
      # uses: MrSquaare/ssh-setup-action@8ed91aadfe85793a7db7d339cab95f07c50686e4
      uses: MrSquaare/ssh-setup-action@v1.0.1
      with:
        # SSH hosts
        host: challenger.tiar.be
        # SSH private key
        private-key: ${{secrets.PRIVATE_KEY}}

    - name: Start Websockets server
      run: 'ssh music@challenger.tiar.be sudo supervisorctl restart MUSICPROJECT:'
      
      
      
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
